"""
Post-LLM Claim / Evidence Validation Layer.
Validates that every claim generated by AI is supported by verified database evidence.
Rejects or strips unsupported claims and ensures absolute anti-hallucination compliance.
"""

from typing import Dict, Any, List, Tuple
from src.utils.logger import get_logger

logger = get_logger("ClaimEvidenceValidator")

class ClaimEvidenceValidator:
    """Validates generated AI claims against verified evidence package items."""

    def validate_and_filter(
        self,
        ai_response: Dict[str, Any],
        verified_evidence: List[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """
        Validates generated AI response claims.
        Strips unsupported claims, filters citations, and enforces exact trust boundary.
        """
        evidence_status_map = {
            item.get("evidence_type"): {
                "status": item.get("status"),
                "data": item.get("data") or {}
            } for item in verified_evidence
        }

        validated_citations = []
        rejected_claims = []

        raw_citations = ai_response.get("evidence_citations", [])
        for cite in raw_citations:
            claim_text = cite.get("claim", "")
            refs = cite.get("evidence_refs", [])
            valid_refs = []

            for ref in refs:
                ev_info = evidence_status_map.get(ref)
                if ev_info and ev_info["status"] in ("AVAILABLE", "UNVERIFIED"):
                    valid_refs.append(ref)

            if valid_refs:
                validated_citations.append({
                    "claim": claim_text,
                    "evidence_refs": valid_refs
                })
            else:
                rejected_claims.append(claim_text)
                logger.warning(f"REJECTED unsupported claim: '{claim_text}' (Refs: {refs})")

        # Anti-hallucination check on key facts
        raw_key_facts = ai_response.get("key_facts", [])
        validated_key_facts = []

        for fact in raw_key_facts:
            # Check if fact mentions delivery when delivery evidence is MISSING
            deliv_status = evidence_status_map.get("delivery_confirmation", {}).get("status", "MISSING")
            ship_status = evidence_status_map.get("shipping_confirmation", {}).get("status", "MISSING")

            fact_lower = fact.lower()

            if "delivered on" in fact_lower or "delivered successfully" in fact_lower or "delivered at" in fact_lower:
                if deliv_status not in ("AVAILABLE", "UNVERIFIED"):
                    logger.warning(f"REJECTED key fact hallucinating delivery without evidence: '{fact}'")
                    continue
            
            if "shipped on" in fact_lower or "tracking number" in fact_lower:
                if ship_status not in ("AVAILABLE", "UNVERIFIED"):
                    logger.warning(f"REJECTED key fact hallucinating shipping without evidence: '{fact}'")
                    continue

            validated_key_facts.append(fact)

        # Ensure limitations list reflects missing, unverified, or invalid evidence
        limitations = list(ai_response.get("limitations", []))
        for ev_type, info in evidence_status_map.items():
            if info["status"] == "MISSING":
                lim_str = f"Missing verified '{ev_type}' record in database."
                if lim_str not in limitations:
                    limitations.append(lim_str)
            elif info["status"] == "UNVERIFIED":
                lim_str = f"Evidence '{ev_type}' is UNVERIFIED or incomplete."
                if lim_str not in limitations:
                    limitations.append(lim_str)
            elif info["status"] == "INVALID":
                lim_str = f"Evidence '{ev_type}' is INVALID or incomplete."
                if lim_str not in limitations:
                    limitations.append(lim_str)

        # Enforce merchant position rules
        position = ai_response.get("merchant_position", "INSUFFICIENT_EVIDENCE")
        available_count = sum(1 for info in evidence_status_map.values() if info["status"] == "AVAILABLE")
        missing_count = sum(1 for info in evidence_status_map.values() if info["status"] == "MISSING")

        deliv_stat = evidence_status_map.get("delivery_confirmation", {}).get("status")

        if missing_count >= 2 or available_count < 2:
            position = "INSUFFICIENT_EVIDENCE"
        elif missing_count > 0 or deliv_stat != "AVAILABLE":
            if position == "CONTEST":
                position = "PARTIAL_CONTEST" if available_count >= 2 else "INSUFFICIENT_EVIDENCE"

        ai_response["key_facts"] = validated_key_facts
        ai_response["evidence_citations"] = validated_citations
        ai_response["limitations"] = limitations
        ai_response["merchant_position"] = position

        return ai_response
